### ISSUE TITLE
Run button feedback when program doesn't compile

### ISSUE THREAD

**Issue by uncomputable** [uncomputable/simfony-webide#25]
There should be a "rejection" animation when the run button is clicked on a non-compiling program. Something like a red flash with the button wiggling from left to right.

Right now, when the parse errors are outside of the screen, there is no feedback at all.

**Comment by dpet** [comment]
For now I can disable the button and add disabled styling when there are parsing errors.

**Comment by uncomputable** [comment]
Fixed in #37
